global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, evaluate rules every 15 seconds.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - 127.0.0.1:8080

  - job_name: api01
    scrape_interval: 5s
    metrics_path: "/q/metrics"
    static_configs:
    - targets:
      - 127.0.0.1:9001
      
  - job_name: postgres
    scrape_interval: 5s
    static_configs:
    - targets:
      - 127.0.0.1:9187
